{% set name = "de-studiensuche" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/de-studiensuche-{{ version }}.tar.gz
  sha256: 5e37f916879df19215210eb32fbeb64e7bec70fde7a005902785b5eeebeb0383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.studiensuche
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/studiensuche-api
  summary: Arbeitsagentur Studiensuche API
  license: Apache-2.0
  license_file: 
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
